#!/usr/bin/env python

# Copyright (c) 2018  Floyd Terbo

import json
import sys

import scotus.filters
import scotus.outputs
import scotus.queries
import scotus.sources

# analysis-engine '{"sources" : [("docket", {"term" : 17, "paid" : true, "ifp" : true})],
#                   "filters" : [],
#                   "queries" : [("petition-ngram", {"query_term" : "qualified immunity", "min_count" : 2})],
#                   "output" : "docket-oneline"}'


def engine (sources, filters, queries, output):
  print sources
  pass

if __name__ == '__main__':
  print sys.argv
  kwargs = json.loads(sys.argv[1])
  engine(**kwargs)
