#!/usr/bin/env python

# Copyright (c) 2018  Floyd Terbo

import argparse
import datetime
import json
import logging
import os
import os.path
import sys
import time
import urllib

import BeautifulSoup as BS
import requests

logging.basicConfig(level=logging.INFO)

HEADERS = {"User-Agent" : "SCOTUS Opinion Grabber (https://github.com/fterbo/scotus-tools)"}
BASE = "https://www.supremecourt.gov/"


def GET (url):
  logging.debug("GET: %s" % (url))
  return requests.get(url, headers=HEADERS)


def parse_args ():
  parser = argparse.ArgumentParser()
  parser.add_argument("-t", "--term", dest="term", type=int)
  parser.add_argument("--root", dest="root", type=str, default=".")
  args = parser.parse_args()
  return args

def scanOpinions (path, opts):
  r = GET("%s/opinions/slipopinion/%d" % (BASE, opts.term))
  if r.status_code != 200:
    print r.status_code
    sys.exit(1)

  root = BS.BeautifulSoup(r.content)

  # Opinions are (at the moment, anyhow) organized in expandable panels, which are conveniently
  # identified by using the "panel-body" class.  We could be as greedy as ordergrab is and avoid the
  # complications here, but we can glean some more data out of the table that might be useful if we
  # try to parse more structure
  panels = root.findAll("div", {"class" : "panel-body"})
  for panel in panels:
    rows = panel.findAll("tr")
    for row in rows[1:]:
      odata = {}
      cells = row.findAll("td")
      odata["R"] = int(cells[0].text)

      opath = "%s/%d" % (path, odata["R"])
      os.makedirs(opath)

      odata["date"] = datetime.datetime.strptime(cells[1], "%m/%d/%y")
      odata["docket"] = int(cells[2].split("-")[1])
      aelem = cells[3].find("a")
      r = GET(aelem["href"])
      with open("%s/%s" % (opath, aelem["href"].split("/")[-1]), "w+") as f:
        f.write(r.content)
      odata["blurb"] = aelem.get("title")

      revised = cells[4].find("a")
      if revised:
        r = GET(revised["href"])
        with open("%s/%s" % (opath, revised["href"].split("/")[-1]), "w+") as f:
          f.write(r.content)

      odata["justice"] = cells[5]
      odata["prelim-part"] = cells[6]

      with open("%s/info.json" % (opath)) as f:
        f.write(json.dumps(odata))


if __name__ == '__main__':
  opts = parse_args()
  path = "%s/OT-%d/opinions" % (opts.root, opts.term)
  try:
    os.makedirs(path)
  except OSError:
    pass

  scanOpinions (path, opts)
