#!/usr/bin/env python

# Copyright (c) 2018  Floyd Terbo

import os
import sys

import PyPDF2

SECTIONS = {
  "CERTSUM" : "CERTIORARI -- SUMMARY DISPOSITION",
  "PENDING" : ["ORDERS IN PENDING CASES", "ORDER IN PENDING CASE"],
  "CERTDENY" : "CERTIORARI DENIED",
  "HABEASDENY" : "HABEAS CORPUS DENIED",
  "MANDAMUSDENY" : "MANDAMUS DENIED",
  "REHEARDENY" : ["REHEARINGS DENIED", "REHEARING DENIED"],
  "DISCIPLINE" : "ATTORNEY DISCIPLINE",
  "PROHIBDENY" : "PROHIBITION DENIED",
  "GRANTS" : "CERTIORARI GRANTED",
  "DECISION" : "Cite as"
}

def count_seal(fname):
  seal_count = 0
  fo = open(fname, "rb")
  reader = PyPDF2.PdfFileReader(fo)
  for page in range(reader.numPages):
    for line in reader.getPage(page).extractText().split("\n"):
      if line.count("seal"):
        seal_count += 1
  if seal_count:
    print "%s: %d" % (fname, seal_count)

def count_word(word, fname):
  word_count = {}
  fo = open(fname, "rb")
  reader = PyPDF2.PdfFileReader(fo)
  cur_section = None
  for page in range(reader.numPages):
    for line in reader.getPage(page).extractText().split("\n"):
      for shortname,secname in SECTIONS.items():
        if isinstance(secname, (list, tuple)):
          for name in secname:
            if line.count(name):
              cur_section = shortname
              break
        else:
          if line.count(secname):
            cur_section = shortname
            break
      if line.count(word):
        word_count.setdefault(cur_section, [0])[0] += 1
  if word_count:
    for section,count in word_count.items():
      print "%s: [%s] %d" % (fname, section, count[0])

def count_section_word (section, word, name):
  sec_text = SECTIONS[section]
  in_section = False
  word_count = 0
  fo = open(name, "rb")
  reader = PyPDF2.PdfFileReader(fo)
  for page in range(reader.numPages):
    for line in reader.getPage(page).extractText().split("\n"):
      if in_section:
        for possible in SECTIONS.values():
          if isinstance(possible, (list, tuple)):
            for name in possible:
              if line.count(name):
                in_section = False
                break
          else:
            if line.count(possible):
              in_section = False
              break
        if line.count(word):
          word_count += 1
      else:
        if line.count(sec_text):
          in_section = True

  if word_count:
    print "[%s] %s: %d" % (sec_text, name, word_count)


def list_word(word):
  for name in os.listdir("."):
    if name.count(".pdf"):
      count_word(word, name)

def list_section_word (word, section):
  for name in os.listdir("."):
    if name.count(".pdf"):
      count_section_word(section, word, name)

if __name__ == '__main__':
  os.chdir("OT-%d/orders/" % (int(sys.argv[1])))
  if sys.argv[2] == "ANY":
    list_word(sys.argv[3])
  else:
    list_section_word(sys.argv[3], sys.argv[2])
  os.chdir("..")
